name = "Nerts"
author = "Smudge"
link = ""
year = 2022

[formats.standard]
matrix = [["x", "l", "d", "p", "v", "z", "k", "o", "u", ";"],
["n", "r", "t", "s", "g", "y", "h", "e", "i", "a", "/"],
["q", "j", "m", "c", "w", "b", "f", "'", ",", "."]]

map = {}
home_row = 1
